name: Build and Push Flask Docker Image

on:
  push:
    branches:
      - main
      - feature/dahye
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: List directory contents
      run: ls -tl
      
    - name: Build Docker Image
      run: |
        docker build -t de52/flask_stock:latest .

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        
    - name: Push Docker Image
      run: |
        docker push de52/flask_stock:latest
