name: Flask CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: run ls -tl
      run: ls -tl
      
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask
        pip install -r requirements.txt
        
    - name: Set up environment
      env:
        POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
        POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
       
    - name: Run Flask Tests
      run: |
        cd flask;
        python dashboard.py &
        sleep 10
        curl http://127.0.0.1:5000/
