name: git pull on EC2

on:
  push:
    branches:
      - main  # or whichever branch you prefer
      - feature/jongwook
      
jobs:
  test-ec2-connection:
    runs-on: ubuntu-latest

    steps:
    - name: "context"
      env:
        COMMIT_ID: ${{ github.sha }}
      run: echo "Commit id => $COMMIT_ID"
    - name: Execute g on EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
      run: |
        echo "$PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST "\
        cd /home/ubuntu/Front/flask; \
        fuser -k 5000/tcp; \
        source env/bin/activate; \
        nohup python3 app.py > output.log 2>&1 & \
        sleep 10; \
        curl http://127.0.0.1:5000"
        rm -f private_key.pem
