name: Integrated CI

on:
  push:
    branches:
      - main
      - feature/jongwook

jobs:
  build-flask:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setting up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask

    - name: Run Flask Tests
      run: |
        # Flask
        python app.py &
        sleep 10
        curl http://127.0.0.1:5000/

  test-ec2-connection:
    runs-on: ubuntu-latest
    needs: build-flask

    steps:
    - name: "context"
      env:
        COMMIT_ID: ${{github.sha}}
      run: echo "Commit ID => $COMMIT_ID"
    - name: Execute ls -tl on EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        HOST: ${{secrets.EC2_HOST}}
        USER: ${{secrets.EC2_USER}}
      run: |
        echo "$PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST "\
        ls -tl; \
        echo 'Hello, World!'"
        rm -f private_key.pem
