name: Test EC2 Connection

on:
  push:
    branches:
      - main  # or whichever branch you prefer
      - feature/jongwook
      
jobs:
  test-connection:
    runs-on: ubuntu-latest

    steps:
    - name: Execute ls -tl on EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
      run: |
        echo "$PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST "ls -tl"
        rm -f private_key.pem
